"""
Django settings for reactions_project project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    env_path = Path(__file__).resolve().parent.parent.parent / '.env'
    print(f"Loading .env from: {env_path}")
    print(f".env exists: {env_path.exists()}")
    load_dotenv(dotenv_path=env_path)
    print(f"After load_dotenv, DJANGO_DEBUG={os.getenv('DJANGO_DEBUG')}")
except ImportError:
    # python-dotenv not installed, environment variables must be set manually
    print("WARNING: python-dotenv not installed, environment variables must be set manually")
    pass

# VMH configuration
VMH_BASE_URL = os.getenv('VMH_BASE_URL', '').rstrip('/')
VMH_API_KEY = os.getenv('VMH_API_KEY', '')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


def _str_to_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-3x4rk(#0pr)5c&z=52$w_v^gj@jpl^*fw@8fa!wxg(o@3sw#mh'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _str_to_bool(os.getenv('DJANGO_DEBUG', 'False'))

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# File paths
MOL_FILE_PATH = os.getenv('MOL_FILE_PATH', str(BASE_DIR / 'media' / 'mol_files'))
FILE_PATH = os.getenv('FILE_PATH', 'curationTool/reactions/normal_tissue.tsv')

# MATLAB/COBRA Toolbox paths (comma-separated for multiple directories)
SCRIPT_DIRECTORIES = os.getenv('SCRIPT_DIRECTORIES', '').split(',') if os.getenv('SCRIPT_DIRECTORIES') else []
COBRA_PATH = os.getenv('COBRA_PATH', '')
print(f"debug={DEBUG}")
print(f"SCRIPT_DIRECTORIES={SCRIPT_DIRECTORIES}")
print(f"COBRA_PATH={COBRA_PATH}")

# Media serving configuration (useful for containerized development with DEBUG=False)
SERVE_MEDIA = _str_to_bool(os.getenv('SERVE_MEDIA'), DEBUG)

# Allowed hosts
_allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in _allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = [
        '127.0.0.1',
        'localhost',
        '83.70.173.200',
        '192.168.1.49',
        'reconstructor.chatimd.org',
        'reconstructor.humanmetabolism.org',
        'constructor.humanmetabolism.org',
        '0.0.0.0'
    ]

#allow CsrfViewMiddleware
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reactions',
]
#
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reactions_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "reactions/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]


WSGI_APPLICATION = 'reactions_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'curationtooldb1'),
        'USER': os.getenv('POSTGRES_USER', 'saleh'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', '1curationTool1'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = []
_additional_static_dir = BASE_DIR / "static"
if _additional_static_dir.exists():
    STATICFILES_DIRS.append(str(_additional_static_dir))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# In development, serve static files live from the source tree. The manifest
# storage hashes filenames and caches the manifest in memory at server start, so
# edits to CSS/JS would otherwise require `collectstatic` + a server restart to
# appear. In production keep the compressed, hashed manifest storage.
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    WHITENOISE_AUTOREFRESH = True
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
