# Generated by Django 5.0.1 on 2024-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='flagged_reactions', to='reactions.flag'),
        ),
    ]
