# Generated by Django 5.0.1 on 2024-08-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_alter_reaction_organs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='formulas',
            new_name='rxn_formula_abbr',
        ),
    ]
