# Generated by Django 5.0.1 on 2024-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0008_remove_reaction_rxn_formula_abbr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='rxn_formula',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
