# Generated by Django 5.0.1 on 2024-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0009_alter_reaction_rxn_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='rxn_formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
