# Generated by Django 5.0.1 on 2024-08-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0010_alter_reaction_rxn_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='prods_edited',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='subs_edited',
        ),
    ]
