# Generated by Django 5.0.6 on 2025-01-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0012_reaction_stereo_counts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text="True for built-in templates; these shouldn't be edited or deleted.")),
                ('substrates', models.TextField(blank=True, help_text='Comma-separated list of substrates.', null=True)),
                ('products', models.TextField(blank=True, help_text='Comma-separated list of products.', null=True)),
                ('direction', models.TextField(blank=True, help_text='Reaction direction (e.g. "forward", "bidirectional")', null=True)),
                ('substrates_types', models.TextField(blank=True, null=True)),
                ('products_types', models.TextField(blank=True, null=True)),
                ('subsystem', models.TextField(blank=True, null=True)),
                ('subs_comps', models.TextField(blank=True, null=True)),
                ('prods_comps', models.TextField(blank=True, null=True)),
                ('subs_sch', models.TextField(blank=True, null=True)),
                ('prods_sch', models.TextField(blank=True, null=True)),
                ('Organs', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this template. Null if it is a default template.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reactions.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='created_by_users', to='reactions.reactiontemplate'),
        ),
    ]
