# Generated by Django 5.0.6 on 2025-02-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0013_reactiontemplate_user_templates'),
        ('reactions', '0016_reaction_description'),
    ]

    operations = [
    ]
