# Generated by Django 5.0.6 on 2025-02-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0017_merge_20250204_1728'),
        ('reactions', '0025_reaction_metabolite_inchi_keys_and_more'),
    ]

    operations = [
    ]
