# Generated by Django 5.0.1 on 2025-11-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0026_merge_20250212_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.TextField(blank=True)),
                ('hgnc_id', models.CharField(max_length=20, unique=True)),
                ('entrez_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('aliases', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='savedmetabolite',
            name='inchi_key',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='savedmetabolite',
            name='original_identifier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reactions', models.ManyToManyField(related_name='in_workspaces', to='reactions.reaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='reactions.user')),
            ],
        ),
    ]
