# Generated by Django 5.0.6 on 2025-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0026_merge_20250212_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactiontemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
