# Generated by Django 5.0.6 on 2025-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0027_alter_savedmetabolite_inchi_key'),
        ('reactions', '0027_reactiontemplate_description'),
    ]

    operations = [
    ]
