# Generated by Django 5.0.1 on 2026-06-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0028_vmh_addition_recordkeeping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReactionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reaction_groups",
                        to="reactions.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReactionGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="reactions.reactiongroup",
                    ),
                ),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="reactions.reaction",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "added_at"],
                "unique_together": {("group", "reaction")},
            },
        ),
        migrations.AddField(
            model_name="reactiongroup",
            name="reactions",
            field=models.ManyToManyField(
                related_name="reaction_groups",
                through="reactions.ReactionGroupMembership",
                to="reactions.reaction",
            ),
        ),
    ]
