# Generated by Django 5.0.1 on 2025-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0029_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('name', models.TextField(blank=True)),
                ('hgnc_id', models.CharField(max_length=20, unique=True)),
                ('entrez_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('aliases', models.TextField(blank=True)),
            ],
        ),
    ]
