# Generated by Django 5.0.1 on 2026-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0030_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="vmh_added_via_constructor",
            field=models.BooleanField(default=False),
        ),
    ]
