@startuml 

    class "Explanation of the symbols used" as DESCRIPTION #FFF {
    - AutoField (identifiers)
    ..
    + Regular field (anything)
    ..
    # ForeignKey (ManyToMany)
    ..
    ~ ForeignKey (OneToOne, OneToMany)
    --
}


class "auth.Permission <Authentication and Authorization>" as auth.Permission #e8f4d6 {
    permission
    ..
    The permissions system provides a way to assign permissions to specific
    users and groups of users.
    The permission system is used by the Django admin site, but may also be
    useful in your own code. The Django admin site uses permissions as follows:
        - The "add" permission limits the user's ability to view the "add" form
          and add an object.
        - The "change" permission limits a user's ability to view the change
          list, view the "change" form and change an object.
        - The "delete" permission limits the ability to delete an object.
        - The "view" permission limits the ability to view an object.
    Permissions are set globally per type of object, not per specific object
    instance. It is possible to say "Mary may change news stories," but it's
    not currently possible to say "Mary may change news stories, but only the
    ones she created herself" or "Mary may only change news stories that have a
    certain status or publication date."
    The permissions listed above are automatically created for each model.
    --
    - id (AutoField) - 
    + name (CharField) - 
    ~ content_type (ForeignKey) - 
    + codename (CharField) - 
    --
}
auth.Permission -- contenttypes.ContentType


class "auth.Group <Authentication and Authorization>" as auth.Group #e8f4d6 {
    group
    ..
    Groups are a generic way of categorizing users to apply permissions, or
    some other label, to those users. A user can belong to any number of
    groups.
    A user in a group automatically has all the permissions granted to that
    group. For example, if the group 'Site editors' has the permission
    can_edit_home_page, any user in that group will have that permission.
    Beyond permissions, groups are a convenient way to categorize users to
    apply some label, or extended functionality, to them. For example, you
    could create a group 'Special users', and you could write code that would
    do special things to those users -- such as giving them access to a
    members-only portion of your site, or sending them members-only email
    messages.
    --
    - id (AutoField) - 
    + name (CharField) - 
    # permissions (ManyToManyField) - 
    --
}
auth.Group *--* auth.Permission


class "auth.User <Authentication and Authorization>" as auth.User #e8f4d6 {
    user
    ..
    Users within the Django authentication system are represented by this
    model.
    Username and password are required. Other fields are optional.
    --
    - id (AutoField) - 
    + password (CharField) - 
    + last_login (DateTimeField) - 
    + is_superuser (BooleanField) - Designates that this user has all permissions
without explicitly assigning them.
    + username (CharField) - Required. 150 characters or fewer. Letters, digits and
@/./+/-/_ only.
    + first_name (CharField) - 
    + last_name (CharField) - 
    + email (EmailField) - 
    + is_staff (BooleanField) - Designates whether the user can log into this admin
site.
    + is_active (BooleanField) - Designates whether this user should be treated as
active. Unselect this instead of deleting accounts.
    + date_joined (DateTimeField) - 
    # groups (ManyToManyField) - The groups this user belongs to. A user will get
all permissions granted to each of their groups.
    # user_permissions (ManyToManyField) - Specific permissions for this user.
    --
}
auth.User *--* auth.Group
auth.User *--* auth.Permission


class "contenttypes.ContentType <Content Types>" as contenttypes.ContentType #d6f4de {
    content type
    ..
    ContentType(id, app_label, model)
    --
    - id (AutoField) - 
    + app_label (CharField) - 
    + model (CharField) - 
    --
}


@enduml
