# Generated by Django 5.0.1 on 2025-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0025_reaction_metabolite_inchi_keys_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedmetabolite",
            name="original_identifier",
            field=models.TextField(blank=True, null=True),
        ),
    ]
