# Generated by Django 5.0.1 on 2025-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0026_alter_savedmetabolite_original_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedmetabolite",
            name="inchi_key",
            field=models.CharField(max_length=27),
        ),
    ]
